# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # CREDENTIAL
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: AKIAZWLO5FSYI65ZZAP3
         aws-secret-access-key: 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
         aws-region: us-east-1
         
      - name: Login to Amazon ECR
        id: cloud_user
        uses: aws-actions/amazon-ecr-login@v1
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Run docker build and push script
        run: |
         docker build -t my-image:v2 .
         docker tag my-image:v2 666489400496.dkr.ecr.us-east-1.amazonaws.com/aws-repository:v2
         docker image list
         docker push 666489400496.dkr.ecr.us-east-1.amazonaws.com/aws-repository:v2
