# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
         docker build --tag my-image:v2 . 
      - name: Push to ECR
        id: ecr
        uses: nilesh-sudo/Terraform@master
        with:
          access-key-id: ${{ secrets.AKIAY7O5Z2NGMKKT7P4R }}
          secret-access-key: ${{ secrets.nZd96K4TxUEmAZOZ7OJ9pCiRbA8mOuUglOOE69yR }}
          region: us-east-1
          image: my-image:v2
