# This is a basic workflow to help you get started with Actions

name: github to docker-hub

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker  Hub
        env:
         DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 112125112125/docker-hub:latest
